### ISSUE TITLE
Roadmap v3

### ISSUE THREAD

**Issue by nshiab** [nshiab/simple-data-analysis#415]
Breaking changes:
- [x] Change class names. SimpleDB => SimpleWebDB. SimpleNodeDB => SimpleDB. It makes more sense, since SDA can be used with many JS runtimes.
- [x] New classes. SimpleDB and SimpleTable.
- [x] Removing SimpleGeo
- [x] Change getLength to getNbRows,  getWidth to getNbColumns, and getValuesCount to getNbValues
- [x] Removing all parameters `columns: [string, string]` and replacing them by `column1: string, column2: string`

Geospatial capabilities. Adding these functions from the spatial extension:
- [x] ST_Point
- [x] ST_Area_Spheroid
- [x] ST_Buffer
- [x] ST_Centroid
- [x] ST_Covers
- [x] ST_Difference
- [ ] ST_Distance_Spheroid
- [x] ST_DWithin_Spheroid
- [x] ST_FlipCoordinates
- [x] ST_Length_Spheroid
- [x] ST_GeometryType
- [x] ST_Perimeter_Spheroid
- [x] ST_Intersection
- [x] ST_Intersects
- [x] ST_IsValid
- [x] ST_ReducePrecision
- [x] ST_SimplifyPreserveTopology
- [x] ST_Union
- [x] ST_X
- [x] ST_Y
- [x] Save projections as properties. Use it for getProjection, reproject, and add a new method .toWGS84 (lat, lon axis order).
- [x] getGeoData to retrieve data as geojson

Other:
- [x] Add geo example in README and at the top of the tables classes
- [x] Adding tests with Bun
- [x] Extension to be loaded just when necessary with loadArray, loadData, and loadGeoData.
